// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pybqxjvjvknxfedtkijq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5YnF4anZqdmtueGZlZHRraWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDQxMDMsImV4cCI6MjA2OTk4MDEwM30.M2HB6QFZArNp4fJGCwquYnIlqsF08UKh5rbE5kdr5dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});